### ISSUE TITLE
Admin password reset by default

### ISSUE THREAD

**Issue by chrisolof** [vampd/drupal#27]
So it appears that following a database import, by default, vampd-drupal will attempt to reset a password for a user by the name of "admin."  This is great if you're aware of this default functionality and you actually have a user with the username of "admin", but if you're not expecting it and don't have a user by that name in your Drupal DB it results in an error on spin-up.

Don't get me wrong - I think this functionality is awesome - but I'd suggest we turn it off by default and document how to use it (unless documentation is already present!) as one of the cool features of Vampd.

**Comment by timodwhit** [comment]
That makes sense to me. I beleive the original thought was that the user is stored in the databag, so that should be the canonical source. 

I agree that the databag should be default. 

You going to Pull Request this?

**Comment by timodwhit** [comment]
I don't think we should reset the password by default or even use a password setting in the databag/recipe. 

Even though the pass etc can be encrypted in a databag it seems an unnecessary risk to take for the recipe. What if instead we recommend using `drush uli` to create an admin 1 user login link. Without a pass set, the password would be set to a random hash using drush, and can be reset using the `drush uli`.

@chrisolof or @arknoll what do you think?

**Comment by chrisolof** [comment]
Drush uli is typically my route - what if we start by disabling this admin pw reset by default, and open a new issue as to whether or not we should have the functionality in the recipe at all?  The open PR would stop this reset from occurring by default.
